@token ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdvbWV6MTIiLCJmdWxsbmFtZSI6ImFuZHJlcyBnb21leiIsImVtYWlsIjoiZ29tZTMzekBnbWFpbC5jb20iLCJpYXQiOjE3MjQwMzE3NjcsImV4cCI6MTcyNDA3NDk2N30.z1FmRU9p6-mrGvfDImy2qkHP0e7E-K2oK6WNcURzYUQ"

GET https://edpeimqbi3.execute-api.us-east-1.amazonaws.com/prod/users/refresh-page
Authorization:{{token}}
###

POST https://edpeimqbi3.execute-api.us-east-1.amazonaws.com/prod/users/create
Content-Type: application/json

{
    "username": "Gomez12",
    "email": "gome33z@gmail.com",
    "fullname": "Andres Gomez",
    "password": "1234567*",
    "repassword": "1234567*"
}
###

GET   https://i1hfs9poyc.execute-api.us-east-1.amazonaws.com/prod/places?id=f28fa28b-9d25-410a-9dcd-90a799702255
###

DELETE  https://i1hfs9poyc.execute-api.us-east-1.amazonaws.com/prod/places?id=
###


PUT https://i1hfs9poyc.execute-api.us-east-1.amazonaws.com/prod/places?id=aa4bd953-9c0c-4eaf-baa1-85a4bc2fefa8
Content-Type: application/json

{
    "location": "Venezuela"
}
###